 CREATE TABLE TBL_ALUNO(
  ID_ALUNO INTEGER NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  CIDADE VARCHAR(100) NOT NULL,
  CPF VARCHAR(14) NOT NULL,
  CEP VARCHAR(10) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID_ALUNO)
);

INSERT INTO TBL_ALUNO VALUES (1, 'Italo Henrique', 'Belo Horizonte', '13.147.056-24','30644-150', 'italodssouza@gmail.com');
INSERT INTO TBL_ALUNO VALUES (2, 'Fernanda Melo', 'Montreux', '13.187.157-16','30644-150', 'fernanda.so@gmail.com');
INSERT INTO TBL_ALUNO VALUES (3, 'Aline Suyenne', 'Contagem', '12.954.087-73','30644-150', 'alinesuyenne@gmail.com');
INSERT INTO TBL_ALUNO VALUES (4, 'Leandro Caldeira', 'Belo Horizonte', '13.357.974-75','30644-150', 'leandro.jesus@gmail.com');


SELECT * FROM TBL_ALUNO;

CREATE TABLE TBL_CONTRATO(
  ID_CONTRATO INTEGER NOT NULL PRIMARY KEY,
  DATA DATE NOT NULL,
  ALUNO_ID INTEGER NOT NULL,
  TOTAL NUMBER NOT NULL,
  FOREIGN KEY (ALUNO_ID) REFERENCES TBL_ALUNO(ID_ALUNO)
);

ALTER TABLE TBL_CONTRATO ADD DESCONTO NUMBER DEFAULT 100;
--ALTER TABLE TBL_CONTRATO DROP COLUMN DESCONTO;--

CREATE SEQUENCE SEQ_CONTRATO START WITH 1;

INSERT INTO TBL_CONTRATO VALUES (SEQ_CONTRATO.NEXTVAL, SYSDATE, 2, 1500,100);
INSERT INTO TBL_CONTRATO VALUES (SEQ_CONTRATO.NEXTVAL,  ADD_MONTHS(SYSDATE,2), 2, 1352, 500);

SELECT * FROM TBL_CONTRATO;
SELECT * FROM TBL_CONTRATO WHERE
  DATA > ADD_MONTHS(SYSDATE, -1);

UPDATE TBL_CONTRATO SET
  data = SYSDATE,
  total = 1400
  WHERE total = 1352;

--para confirmar alterações--
COMMIT;

--para desfazer alterações--
ROLLBACK;